author: 浣熊say # 作者
description: 浣熊say小站&央国企指南，帮助大家一站式快速获取央国企信息，社招、校招央国企不迷路！
keyword: hexo-theme, vuejs

excerpt_link: Read more

menu:
 主页:         # 主页
  url: ""   # 主页url

 央国企面试指南:
  url:  央国企面试指南/1.央国企面试指南简介/央国企面试指南简介

 央国企笔试指南:
  url:  央国企笔试指南/1.简介/1.央国企笔试指南
# 央国企知识:
#  url: 央国企知识/1.央国企知识简介/央国企知识简介

 央国企名录:
  url: 央国企名录/2.中央企业名录/2024-center-enterpries-list

 Java面试指南:
  url: /Java面试指南/1.简介/简介

 公众号:
  url: about/我的公众号/我的公众号
#  url: tags

 知识星球:
  url: about/我的星球/知识星球
#  url: archives

 关于我:        #关于
  url: about/关于我/1.终于【浣熊say-央国企面试指南】网页版上线了！

tagMap:
 成都央国企指南:


# highlight
highlight:
  tomorrow

# Enable cache
cache: true

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set utterances, gitment, uyan or disqus
comment: utterances

# utterances config
utterances_repo:                # e.g. GitHubAccount/RepoForUtterances
utterances_issue_term: pathname # you can see other available options at 'https://utteranc.es/'
utterances_theme: github-light  # you can see other available options at 'https://utteranc.es/'

# gitment config
gitment_owner: hxsay
gitment_repo: yanm1ng.github.io
gitment_oauth_id: 0f87e490e00ee3fd87ef
gitment_oauth_secret: 4a9d2b148e7971c2201ad12131ce8bf8159ccd2e

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id: 
google_analytics: 
# disqus config
disqus_shortname: 

about: 
  banner: ""
  avatar: https://files.mdnice.com/user/14113/6243e9c2-9fa8-4b96-9058-7676287cbda6.png
  description: "就职于成都某央企，业余时间帮助大家总结央国企招聘、面试信息，希望帮助大家成功进入央国企～"
  weibo_username: 浣熊say
  twitter_username: 浣熊say
  github_username: hxsay
  zhihu_username: 浣熊say
  douban_username: 浣熊say
  linkedin_username: 

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Local Search Support
local_search:
  enable: true

# China Registration
# e.g. 京ICP备12345678号-1
icp:
  enable: false
  number: 京ICP备12345678号-1 # e.g. 京ICP备12345678号-1
# e.g. 京公网安备 12345678901234号
ga:
  enable: false
  province: 京           # e.g. 京
  number: 12345678901234 # e.g. 12345678901234

